### ISSUE TITLE
Dog-API is not deprecated

### ISSUE THREAD

**Issue by kinduff** [DukeNgn/Dog-facts-API#3]
Hello, owner of https://github.com/kinduff/dog-api here.

I noticed you mention that my API is deprecated and the support is minimal.

This is not true. API has been running since 2016, with stability issues but lately 100% uptime.

While I appreciate another port, just wanted to say hi and let this clear.

**Comment by DukeNgn** [comment]
@kinduff 

Hi,
Truly apologize for saying your API is deprecated. I created this project 1 year ago because I couldn't use your API at the time and got frustrated, so decided to port the data and maintain it by myself.
Nevertheless, thanks for your effort in maintaining the project and I'll definitely update the description 👍

**Comment by kinduff** [comment]
@DukeNgn Makes sense! Thanks a lot, and looking forward to do some collaboration if you're up to that.
